### ISSUE TITLE
Use current context namespace as default

### ISSUE THREAD

**Issue by raghavan-arvind** [kei6u/kubectl-secret-data#10]
A pretty common usecase I'd have is to just run `kubectl secretdata <secret name>` and have it run against the current namespace in the kube context. Any objection to adding this feature?

**Comment by keisku** [comment]
@raghavan-arvind Thanks for your feedback! I'll take a look at it.

**Comment by pratikkumar-mohite** [comment]
hey @keisku I would like to work on it, can you please assign to me?

**Comment by keisku** [comment]
Assigned to @pratikkumar-mohite

**Comment by pratikkumar-mohite** [comment]
@keisku can you please review? https://github.com/keisku/kubectl-secretdata/pull/12
